version: "3"
services:
  nursery_nextjs:
    container_name: nursery_nextjs
    build:
      context: ./nursery_front
      dockerfile: Dockerfile_dev
    environment:
      - NEXT_PUBLIC_END_POINT=http://192.168.2.102:8000
    command: yarn dev
    volumes:
      - ./nursery_front:/nursery_front
      - /nursery_front/node_modules
      - /nursery_front/.next
    ports:
      - "3000:3000"
    expose:
      - 3000
    restart: always

  manager_nextjs:
    container_name: manager_nextjs
    build:
      context: ./manager_front
      dockerfile: Dockerfile_dev
    environment:
      - NEXT_PUBLIC_END_POINT=http://192.168.2.102:8000
    command: yarn dev
    volumes:
      - ./manager_front:/manager_front
      - /manager_front/node_modules
      - /manager_front/.next
    ports:
      - "4000:4000"
    expose:
      - 4000
    restart: always
