version: "3"
services:
  postgres:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USER: dpbell
      POSTGRES_PASSWORD: mnb30217
      POSTGRES_DB: fastapi_test
      POSTGRES_HOST: 192.168.2.102
      POSTGRES_PORT: 5432
    ports:
      - "5120:5432"
    expose:
      - 5120
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data/

  # redis:
  #   container_name: data_nursery_redis
  #   restart: always
  #   build:
  #     context: ./db/redis
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4120:6379"
  #   expose:
  #     - 4120
